#!/bin/sh
set -eu

cd "$(dirname "$(realpath "$0")")"

./build_release || exit 1

triple=i586-"$(rustc -Vv | awk -F ': ' '{ if($1 == "host") print $2 }' | cut --complement -zd - -f 1)"

./target/"$triple"/release/ensure_no_std
