name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - run: "rustup component add clippy"
    - uses: actions/checkout@v2
    - run: "cargo build --verbose"
    - run: "cargo doc --verbose"
    - run: "cargo build --verbose --release"
    - run: "cargo outdated --verbose --aggresssive --root-deps-only --exit-code 1"
    - run: "cargo clippy --verbose"
  dos:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          tool: x86_64-unknown-linux-gnu
        - os: windows-latest
          tool: x86_64-pc-windows-msvc
        - os: macOS-latest
          tool: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - run: "rustup component add clippy"
    - run: "rustup component add rust-src --toolchain nightly-${{ matrix.tool }}"
    - uses: actions/checkout@v2
    - run: "cargo +nightly build --verbose --target=i386-pc-dos-msvc.json -Z build-std=core,panic_abort"
    - run: "cargo +nightly doc --verbose --target=i386-pc-dos-msvc.json -Z build-std=core,panic_abort"
    - run: "cargo +nightly build --verbose --release --target=i386-pc-dos-msvc.json -Z build-std=core,panic_abort"
    - run: "cargo +nightly clippy --verbose --target=i386-pc-dos-msvc.json -Z build-std=core,panic_abort"
