name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: ["1.61", "stable", "beta", "nightly"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: "${{ matrix.rust }}"
        override: true
    - run: "rustup component add clippy"
    - uses: actions/checkout@v2
    - run: "cargo build --verbose"
    - run: "cargo doc --verbose"
    - run: "cargo build --verbose --release"
    - run: "cargo outdated --verbose --aggresssive --root-deps-only --exit-code 1"
    - run: "cargo clippy --verbose"
  dos:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: ["1.61", "stable", "beta", "nightly"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: "${{ matrix.rust }}"
        override: true
    - run: "rustup component add clippy"
    - uses: actions/checkout@v2
    - run: "cargo build --verbose --target=i386-pc-dos-msvc.json -Z build-std=core,panic_abort"
    - run: "cargo doc --verbose --target=i386-pc-windows-msvc.json -Z build-std=core,panic_abort"
    - run: "cargo build --verbose --release --target=i386-pc-windows-msvc.json -Z build-std=core,panic_abort"
    - run: "cargo clippy --verbose --target=i386-pc-windows-msvc.json -Z build-std=core,panic_abort"
